update

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -13,20 +13,16 @@ autoload -Uz zmv
 # aliases
 alias tree='lsd --tree'
 alias cat='bat'
-alias ls="lsd"
 alias vim='nvim'
-
-alias l='ls -l'
-alias la='ls -a'
-alias lla='ls -la'
-alias lt='ls --tree'
-alias ll='ls -alF'
 
 alias cls='clear'
 alias ws='cd ~/workspace'
-alias pra='cd ~/workspace/partyround/application'
 alias rel='exec zsh'
 alias mkd='mkdir'
+mkt() {
+  mkdir -p ~/temp/"$1" && cd ~/temp/"$1" || echo "Failed to create directory"
+}
+
 
 # Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
 setopt glob_dots     # no special treatment for file names with a leading dot
@@ -35,6 +31,9 @@ setopt no_auto_menu  # require an extra TAB press to open the completion menu
 
 dot_dir=~/dotfiles
 path=(~/bin /opt/homebrew/anaconda3/bin $dot_dir/scripts $path)
+
+# p10k
+source $dot_dir/zsh/powerlevel10k/powerlevel10k.zsh-theme
 
 # brew
 arch=$(uname -m)
@@ -82,14 +81,10 @@ pyenv_safe_install() {
 export VOLTA_HOME="$HOME/.volta"
 export VOLTA_FEATURE_PNPM=1
 export PATH="$VOLTA_HOME/bin:$PATH"
-source ~/powerlevel10k/powerlevel10k.zsh-theme
-
-# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
-[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
 
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
-source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
-source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
+# source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
+# source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
 
 
 # Load Git completion
@@ -97,3 +92,5 @@ zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
 fpath=(~/.zsh $fpath)
 autoload -Uz compinit && compinit
 
+# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
+[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
